<!DOCTYPE html>
<html style="color:white">
<head><title>Bot</title></head>
<h2 align="center"> CometaBot</h2>
<style>
  body { background: url(https://zastavok.net/temp/wp_2560x1440_textures_1477075539.jpg) }
</style>
<body>
    <form action="https://discord.com/api/oauth2/authorize?client_id=780055783442087946&permissions=8&scope=bot" target="_blank" align="center">
   <button>Добавить бота</button>
  </form>
</body>
</html>
